// Fund & Index Data Module

export const FUND_CATEGORIES = {
  EQUITY_INDEX: 'Equity - Index',
  EQUITY_ACTIVE: 'Equity - Active Fund',
  HYBRID: 'Hybrid',
  DEBT: 'Debt',
};

export const FUNDS = [
  {
    id: 'nifty50',
    name: 'Nifty 50 TRI',
    category: FUND_CATEGORIES.EQUITY_INDEX,
    assetType: 'equity',
    description: 'Tracks the Nifty 50 index, representing the top 50 large-cap companies on NSE.',
    cagr5: 0.155,
    cagr10: 0.128,
    cagr15: 0.134,
    cagr20: 0.142,
    expenseRatio: 0.005,
  },
  {
    id: 'niftynext50',
    name: 'Nifty Next 50 TRI',
    category: FUND_CATEGORIES.EQUITY_INDEX,
    assetType: 'equity',
    description: 'Tracks the Nifty Next 50 index, representing 50 companies ranked 51-100 on NSE by market cap.',
    cagr5: 0.175,
    cagr10: 0.142,
    cagr15: 0.148,
    cagr20: 0.151,
    expenseRatio: 0.005,
  },
  {
    id: 'sensex',
    name: 'S&P BSE Sensex TRI',
    category: FUND_CATEGORIES.EQUITY_INDEX,
    assetType: 'equity',
    description: 'Tracks the BSE Sensex, representing the top 30 large-cap companies on BSE.',
    cagr5: 0.152,
    cagr10: 0.125,
    cagr15: 0.131,
    cagr20: 0.139,
    expenseRatio: 0.005,
  },
  {
    id: 'niftymidcap150',
    name: 'Nifty Midcap 150 TRI',
    category: FUND_CATEGORIES.EQUITY_INDEX,
    assetType: 'equity',
    description: 'Tracks the Nifty Midcap 150 index, providing exposure to mid-cap companies with higher growth potential.',
    cagr5: 0.215,
    cagr10: 0.175,
    cagr15: 0.168,
    cagr20: 0.162,
    expenseRatio: 0.005,
  },
  {
    id: 'hdfc_flexicap',
    name: 'HDFC Flexi Cap Fund',
    category: FUND_CATEGORIES.EQUITY_ACTIVE,
    assetType: 'equity',
    description: 'An actively managed flexi cap fund by HDFC with flexible allocation across large, mid, and small cap stocks.',
    cagr5: 0.185,
    cagr10: 0.155,
    cagr15: 0.148,
    cagr20: 0.158,
    expenseRatio: 0.0153,
  },
  {
    id: 'sbi_bluechip',
    name: 'SBI Blue Chip Fund',
    category: FUND_CATEGORIES.EQUITY_ACTIVE,
    assetType: 'equity',
    description: 'An actively managed large-cap fund by SBI Mutual Fund focusing on blue-chip companies.',
    cagr5: 0.160,
    cagr10: 0.138,
    cagr15: 0.135,
    cagr20: 0.143,
    expenseRatio: 0.0163,
  },
  {
    id: 'ppfas_flexicap',
    name: 'Parag Parikh Flexi Cap Fund',
    category: FUND_CATEGORIES.EQUITY_ACTIVE,
    assetType: 'equity',
    description: 'A unique flexi cap fund with global diversification, investing in Indian and international equities.',
    cagr5: 0.195,
    cagr10: 0.178,
    cagr15: 0.165,
    cagr20: 0.160,
    expenseRatio: 0.0063,
  },
  {
    id: 'axis_smallcap',
    name: 'Axis Small Cap Fund',
    category: FUND_CATEGORIES.EQUITY_ACTIVE,
    assetType: 'equity',
    description: 'An actively managed small cap fund by Axis Mutual Fund targeting high-growth small-cap companies.',
    cagr5: 0.225,
    cagr10: 0.195,
    cagr15: 0.180,
    cagr20: 0.170,
    expenseRatio: 0.0175,
  },
  {
    id: 'icici_bal_adv',
    name: 'ICICI Pru Balanced Advantage',
    category: FUND_CATEGORIES.HYBRID,
    assetType: 'equity',
    description: 'A dynamic asset allocation fund by ICICI Prudential that shifts between equity and debt based on market valuations.',
    cagr5: 0.135,
    cagr10: 0.120,
    cagr15: 0.125,
    cagr20: 0.130,
    expenseRatio: 0.0118,
  },
  {
    id: 'hdfc_bal_adv',
    name: 'HDFC Balanced Advantage Fund',
    category: FUND_CATEGORIES.HYBRID,
    assetType: 'equity',
    description: 'An equity-oriented balanced advantage fund by HDFC that dynamically manages equity-debt allocation.',
    cagr5: 0.145,
    cagr10: 0.130,
    cagr15: 0.135,
    cagr20: 0.140,
    expenseRatio: 0.0075,
  },
  {
    id: 'sbi_magnum_gilt',
    name: 'SBI Magnum Gilt Fund',
    category: FUND_CATEGORIES.DEBT,
    assetType: 'debt',
    description: 'A gilt fund by SBI investing primarily in government securities with low credit risk.',
    cagr5: 0.068,
    cagr10: 0.072,
    cagr15: 0.075,
    cagr20: 0.078,
    expenseRatio: 0.0046,
  },
  {
    id: 'hdfc_corp_bond',
    name: 'HDFC Corporate Bond Fund',
    category: FUND_CATEGORIES.DEBT,
    assetType: 'debt',
    description: 'A corporate bond fund by HDFC investing in high-rated corporate bonds for steady returns.',
    cagr5: 0.072,
    cagr10: 0.076,
    cagr15: 0.079,
    cagr20: 0.081,
    expenseRatio: 0.0036,
  },
  {
    id: 'icici_short_term',
    name: 'ICICI Pru Short Term Fund',
    category: FUND_CATEGORIES.DEBT,
    assetType: 'debt',
    description: 'A short-term debt fund by ICICI Prudential with moderate duration and credit risk management.',
    cagr5: 0.069,
    cagr10: 0.074,
    cagr15: 0.077,
    cagr20: 0.079,
    expenseRatio: 0.0039,
  },
  {
    id: 'ppf',
    name: 'PPF / Fixed Return (7.1%)',
    category: FUND_CATEGORIES.DEBT,
    assetType: 'debt',
    description: 'Public Provident Fund offering a government-guaranteed fixed return of 7.1% with tax-free interest.',
    cagr5: 0.071,
    cagr10: 0.071,
    cagr15: 0.071,
    cagr20: 0.071,
    expenseRatio: 0,
  },
];

export const PRESET_PORTFOLIOS = [
  {
    id: 'conservative',
    name: 'Conservative',
    description: 'Low risk portfolio with 30% equity and 70% debt, suitable for capital preservation with modest growth.',
    allocations: {
      nifty50: 20,
      hdfc_bal_adv: 10,
      hdfc_corp_bond: 40,
      ppf: 30,
    },
  },
  {
    id: 'balanced',
    name: 'Balanced',
    description: 'Moderate risk portfolio with 50% equity and 50% debt, balancing growth with stability.',
    allocations: {
      nifty50: 25,
      niftynext50: 15,
      hdfc_bal_adv: 10,
      hdfc_corp_bond: 30,
      ppf: 20,
    },
  },
  {
    id: 'growth',
    name: 'Growth',
    description: 'Higher risk portfolio with 70% equity and 30% debt, targeting long-term wealth creation.',
    allocations: {
      nifty50: 30,
      niftynext50: 20,
      ppfas_flexicap: 20,
      hdfc_corp_bond: 15,
      ppf: 15,
    },
  },
  {
    id: 'aggressive',
    name: 'Aggressive',
    description: 'High risk portfolio with 90% equity and 10% debt, maximizing long-term growth potential.',
    allocations: {
      nifty50: 30,
      niftynext50: 20,
      ppfas_flexicap: 20,
      axis_smallcap: 20,
      ppf: 10,
    },
  },
];

export const CRASH_EVENTS = [
  { year: 2001, label: 'Dot-com Bust', impact: -20 },
  { year: 2008, label: 'Global Financial Crisis', impact: -52 },
  { year: 2016, label: 'Demonetization', impact: -8 },
  { year: 2020, label: 'COVID-19 Crash', impact: -38 },
  { year: 2025, label: 'Tariff Shock', impact: -5 },
];

export const TAX_RULES = {
  equity: {
    ltcgRate: 0.125,
    stcgRate: 0.20,
    ltcgExemption: 125000,
    holdingPeriodMonths: 12,
  },
  debt: {
    slabRate: 0.30,
    holdingPeriodMonths: 36,
  },
};

export function getFundById(id) {
  return FUNDS.find((fund) => fund.id === id) || null;
}

export function getFundsByCategory(category) {
  return FUNDS.filter((fund) => fund.category === category);
}
